#!/bin/sh

REL="$(dirname "$0")"

if [ -f ".jaz" ]; then
    . "$(pwd)/.jaz"
fi

JIR="$REL/jiri"
JAZZ="$REL/jazz"
JAZ="$JAZZ/jaz"

UPDATE_DEPENDENCIES="true"

REPOCOLOR='\033[1;34m'
NOCOLOR='\033[0m'

case $OSTYPE in
    "msys" )
        alias git='"/c/Program Files/Git/bin/git"'
	     ;;
esac

bootstrap_init () {
    cd "$REL"
    git submodule init
}

bootstrap_update () {
    cd "$REL"
    git submodule update
}

bootstrap () {
    (bootstrap_init) &&
    (bootstrap_update)
}

bootstrap_dispatch () {
    case "$1" in
	"init" )
	    bootstrap_init
	    ;;
	"update" )
	    bootstrap_update
	    ;;
	"" )
	    bootstrap
	    ;;
	* )
	    echo "Unknown bootstrap option : $1"
	    return 1
	    ;;
    esac
}

feedback() {
    case $OSTYPE in
        "msys" )
            echo -e "$1"
	         ;;

        * )
            echo "$1"
            ;;
    esac
}

display_info () {
    feedback "${REPOCOLOR}$1${NOCOLOR}"
    if [ -d "$2" ]; then
	     cd "$2" &&
	     git log -1
    fi
}

display_all_info () {
    (display_info "Sirius" "$REL")
    echo
    (display_info "Jiri" "$JIR")
    echo
    (display_info "Jazz" "$JAZZ")
}

display_status () {
    feedback "${REPOCOLOR}$1${NOCOLOR}"
    if [ -d "$2" ]; then
	     cd "$2" &&
	     git status
    fi
}

display_all_status () {
    (display_status "Sirius" "$REL")
    echo
    (display_status "Jiri" "$JIR")
    echo
    (display_status "Jazz" "$JAZZ")
}

update_dependencies () {
     cd "$REL"
#    git submodule update
}

while getopts "l" OPTION; do
    case $OPTION in
	"l" )
	    UPDATE_DEPENDENCIES="false"
	    ;;
    esac
done

shift $((OPTIND-1))

case "$1" in
    "clone" )
        if [ "$2" = "jazz" ]; then
            git clone https://github.com/jazzscheme/jazz
            exit
        fi
        ;;

	"bootstrap" )
		bootstrap_dispatch $2
		exit
		;;

	"status" )
		display_all_status
		exit
		;;

	"info" )
		display_all_info
		exit
		;;
esac

if [ ! -f "$JAZ" ]; then
	bootstrap
elif $UPDATE_DEPENDENCIES; then
    (update_dependencies)
fi

if [ ! -f "$JAZ" ]; then
	echo "Unable to find jazz/jaz"
	exit 1
fi

exec "$JAZ" "$@"
