#! /bin/sh

TOGETHER=~/Devel/together
INSTALL=$TOGETHER/install
NOTARY=$TOGETHER/notary

# Bail out
set -e

# Setup
echo Copying...
cd $NOTARY
rm -rf together-sirius-prod.app
cp -R $INSTALL/together-sirius-prod together-sirius-prod.app
cd together-sirius-prod.app
rm -rf .jas
jas init -open
jas add .
mv .jas Contents/Resources
cd ..

# Sign
/usr/bin/xattr -r -c -s together-sirius-prod.app
for filename in together-sirius-prod.app/Contents/Libraries/*.dylib; do
    /usr/bin/codesign --force --options runtime --entitlements Entitlements.plist --timestamp --verbose=4 -s "Developer ID Application: Guillaume Cartier (R74FF3EJWG)" --digest-algorithm=sha1,sha256 $filename
done
/usr/bin/codesign --force --options runtime --entitlements Entitlements.plist --timestamp --verbose=4 -s "Developer ID Application: Guillaume Cartier (R74FF3EJWG)" --digest-algorithm=sha1,sha256 together-sirius-prod.app

# Notarize
/usr/bin/ditto -c -k --keepParent together-sirius-prod.app together-sirius-prod.zip
/usr/bin/xcrun altool --notarize-app -f together-sirius-prod.zip --primary-bundle-id com.togethersphere.TogetherSirius -u gucartier@gmail.com -p @keychain:Together\ Test --output-format xml
# /usr/bin/xcrun altool --notarization-info <key-returned-from-previous-command> -u gucartier@gmail.com -p @keychain:Together\ Test
# /usr/bin/xcrun stapler staple -v together-sirius-prod.app
# rm together-sirius-prod.zip

# Notes
# - if the codesigning fails, there will be a LogFileURL that can be pasted into a browser to have a full log
