#! /bin/sh

TOGETHER=~/Devel/together
NOTARY=$TOGETHER/notary
PACKAGE=$TOGETHER/package
MOUNT="/Volumes/Together"

if [[ "$(arch)" == "arm64" ]]; then
  SIRIUS="together-sirius-prod-silicon"
  TEMPLATEDMG="TogetherSiliconTemplate.dmg"
  TOGETHERDMG="Together Apple Silicon.dmg"
else
  SIRIUS="together-sirius-prod-mac"
  TEMPLATEDMG="TogetherTemplate.dmg"
  TOGETHERDMG="Together.dmg"
fi

# Bail out
set -e

cd $PACKAGE

# Setup
if [ -d "$MOUNT" ]; then
	hdiutil detach -quiet "$MOUNT"
fi

if [ -f "$TEMPLATEDMG" ]; then
	rm "$TEMPLATEDMG"
fi

if [ -f "$TOGETHERDMG" ]; then
	rm "$TOGETHERDMG"
fi

# Create and attach template
hdiutil create -quiet -volname Together -fs HFS+ -size 200m -attach $TEMPLATEDMG

# Copy files
cp -R $NOTARY/$SIRIUS.app $MOUNT/Together.app
cp -R background $MOUNT/.background
ln -s /Applications $MOUNT/Applications

# Prettify
/usr/bin/osascript Prettify

# Detach and compress
hdiutil detach -quiet $MOUNT
hdiutil convert $TEMPLATEDMG -quiet -format UDZO -o "$TOGETHERDMG"
rm $TEMPLATEDMG

# Test
# Mount dmg and check that it worked
# Unmount it

# delete $NOTARY/$SIRIUS.app so that there is no url types
# Info.plist active

# Push
# Copy $TOGETHERDMG to website/limited
# commit and push
# go to montreal
# cd /var/www/together
# sudo git pull
